---
# tasks file for vmdeploy
- name: Esxi Deploy
  vsphere_guest:
      vcenter_hostname: esx1.contoso.net
      username: root
      password: "{{ esxi_pass }}"
      guest: "{{ vm_name }}"
      state: powered_on
      vm_disk:
       disk1:
         size_gb: "{{ size_gb }}"
         type: thin
         datastore: "{{ datastore }}"
      vm_nic:
       nic1:
         type: vmxnet3
         network: VM Network
         network_type: standard
      vm_hardware:
         memory_mb: "{{ memory_mb }}"
         num_cpus: "{{ cpu_count }}"
         osid: centos64Guest
         scsi: paravirtual
      vm_hw_version: vmx-08
      esxi:
       hostname: esx1.contoso.net
       datacenter: ha-datacenter

