---
# tasks file for route53dnsup
 - name: Show ipv4address
   debug: var=ipv4address

 - name: Update Route53
   route53:
    command: create
    zone: "{{ hostedzone }}"
    record: "{{ dnsrecordtoupdate }}"
    type: A
    ttl: 300
    value: "{{ ipv4address.stdout }}"
    overwrite: yes
    aws_access_key: "{{ route53_access_key }}"
    aws_secret_key: "{{ route53_secret_key }}"
   register: route53

 - name: Show output
   debug: var=route53
